repos:
  - repo: git://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
      - id: clang-format
  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.10.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
